### ISSUE TITLE
Class Face.java

### ISSUE THREAD

**Issue by sergeybalanin** [top4umba/second#2]
- _Face_ refers _Cube_ (FACE_LENGTH variable). Can't _Face_ accept this value via _matrix.length_ in the constructor?
- (MINOR) _Face_ looks like an immutable object, but it provides setters for modification. Setters (if they are really needed) can preserve immutability using new object creation.
- What's the difference between _flip_ and _flipHorizontally_?

**Comment by top4umba** [comment]
Set FACE_LENGTH in constructor
In cube.getFace create a new matrix and put it in constructor to make Face immutable
Leave only flipHorizontally and rename to flip

**Comment by sergeybalanin** [comment]
_Change flipHorizontally to flip->rotateClockwise->rotateClockwise->rotateClockwise_ - I mean what's the functional difference? Does _flip_ filps vertically or Front-to-Rear?

**Comment by top4umba** [comment]
vertically

**Comment by sergeybalanin** [comment]
Then it's better to have _flipHorizontally_ and _flipVertically_ to avoid such ambiguity.
