### ISSUE TITLE
Class FaceMapper.java

### ISSUE THREAD

**Issue by sergeybalanin** [top4umba/second#3]
All these methods can be methods of FacePosition. Then you can get rid of switch-cases.

**Comment by top4umba** [comment]
How can I get rid of it?

**Comment by sergeybalanin** [comment]
Example: public static int getPointFromFace(FacePosition position, int i, int j, int[][][] cube)
can be moved to FacePosition.getPoint(int i, int j, int[][][] cube).

**Comment by top4umba** [comment]
Move methods from FaceMapper to FacePosition
